#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rr
Version  : 1.1.2
Release  : 5
URL      : https://rubygems.org/downloads/rr-1.1.2.gem
Source0  : https://rubygems.org/downloads/rr-1.1.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
# RR [![Gem Version](https://badge.fury.io/rb/rr.png)](http://badge.fury.io/rb/rr) [![Build Status](https://travis-ci.org/rr/rr.png?branch=master)](https://travis-ci.org/rr/rr) [![Code Climate GPA](https://codeclimate.com/github/rr/rr.png)](https://codeclimate.com/github/rr/rr)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rr-1.1.2
gem spec %{SOURCE0} -l --ruby > rubygem-rr.gemspec

%build
gem build rubygem-rr.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rr-1.1.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rr-1.1.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/Appraisals
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/CREDITS.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/doc/01_test_double.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/doc/02_syntax_comparison.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/doc/03_api_overview.md
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_18_rspec_1.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_18_rspec_1.gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_18_rspec_1_rails_2.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_18_rspec_1_rails_2.gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2.gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2_rails_3.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2_rails_3.gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2_rails_4.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/gemfiles/ruby_19_rspec_2_rails_4.gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/adapters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/adapters/rr_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/autohook.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/blank_slate.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/class_instance_method_defined.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/core_ext/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/core_ext/enumerable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/core_ext/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/core_ext/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/core_ext/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/child_double_definition_create.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/double_definition.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/double_definition_create.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/double_definition_create_blank_slate.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/double_injections/any_instance_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/double_injections/instance.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/double_injection/any_instance_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/double_injection/double_injection_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/double_injection/instance.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/implementation/implementation_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/implementation/proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/implementation/reimplementation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/implementation/strongly_typed_reimplementation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/strategy_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/verification/dont_allow.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/verification/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/verification/stub.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_definitions/strategies/verification/verification_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/double_matches.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/double_definition_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/double_not_found_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/double_order_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/rr_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/spy_verification_errors/double_injection_not_found_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/spy_verification_errors/invocation_count_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/spy_verification_errors/spy_verification_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/subject_does_not_implement_method_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/subject_has_different_arity_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/errors/times_called_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/expectations/any_argument_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/expectations/argument_equality_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/expectations/times_called_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/hash_with_object_id_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/injections/double_injection.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/injections/injection.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/injections/method_missing_injection.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/injections/singleton_method_added_injection.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/decorator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/minitest_4.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/minitest_4_active_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/minitest_active_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/rspec/invocation_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/rspec_1.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/rspec_2.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/test_unit_1.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/test_unit_2.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/test_unit_200.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/test_unit_200_active_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/integrations/test_unit_2_active_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/method_dispatches/base_method_dispatch.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/method_dispatches/method_dispatch.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/method_dispatches/method_missing_dispatch.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/proc_from_block.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/recorded_calls.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/space.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/spy_verification.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/spy_verification_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/any_times_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/at_least_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/at_most_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/integer_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/never_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/non_terminal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/proc_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/range_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/terminal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/times_called_matchers/times_called_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/anything.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/duck_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/hash_including.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/is_a.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/wildcard_matchers/satisfy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/lib/rr/without_autohook.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/rr.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/custom_formatter_for_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/custom_formatter_for_rspec_2.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/defines_spec_suite_tasks.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/fixtures/rubygems_patch_for_187.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/global_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/spec_suite_configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/spec_suite_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites.yml
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1/integration/rspec_1_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1/integration/test_unit_1_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1/integration/test_unit_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1_rails_2/integration/astc_rails_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1_rails_2/integration/rspec_1_rails_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1_rails_2/integration/test_unit_1_rails_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1_rails_2/integration/test_unit_2_rails_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_1_rails_2/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/any_instance_of_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/dont_allow_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/dsl_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/instance_of_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/mock_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/spy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/strong_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/stub_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/functional/wildcard_matchers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/integration/minitest_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/integration/minitest_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/integration/rspec_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/integration/test_unit_200_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/integration/test_unit_2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/support/matchers/wildcard_matcher_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/support/shared_examples/space.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/support/shared_examples/times_called_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/adapters/rr_methods/double_creators_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/adapters/rr_methods/space_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/adapters/rr_methods/wildcard_matchers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/core_ext/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/core_ext/enumerable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/core_ext/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/core_ext/range_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/core_ext/regexp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/double_definitions/child_double_definition_create_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/double_definitions/double_definition_create_blank_slate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/double_definitions/double_definition_create_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/errors/rr_error_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/any_argument_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/anything_argument_equality_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/argument_equality_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/boolean_argument_equality_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/hash_including_argument_equality_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/satisfy_argument_equality_expectation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/any_times_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/at_least_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/at_most_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/integer_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/proc_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/expectations/times_called_expectation/range_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/hash_with_object_id_key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/injections/double_injection/double_injection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/injections/double_injection/double_injection_verify_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/integrations/rspec/invocation_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/integrations/rspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/proc_from_block_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/rr_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/space_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/spy_verification_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/any_times_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/at_least_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/at_most_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/integer_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/proc_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/range_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/times_called_matchers/times_called_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/anything_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/duck_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/hash_including_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/is_a_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/numeric_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2/unit/wildcard_matchers/satisfy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/integration/astc_rails_3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/integration/minitest_4_rails_3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/integration/rspec_2_rails_3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/integration/test_unit_200_rails_3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/integration/test_unit_2_rails_3_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_3/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/integration/astc_rails_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/integration/minitest_4_rails_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/integration/rspec_2_rails_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/integration/test_unit_200_rails_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/integration/test_unit_2_rails_4_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/suites/rspec_2_rails_4/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/adapter_tests/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/adapter_tests/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/adapter_tests/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/adapter_tests/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/command_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/rails_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/rails_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/rails_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/rails_test_unit_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/ruby_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/ruby_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/integration_tests/ruby_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/matchers/be_a_subset_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rails_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rails_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rails_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rails_test_unit_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/ruby_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/ruby_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/ruby_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/ruby_test_unit_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/test_unit_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/project/tests_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test.sqlite3
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_case/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_case/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_case/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_case/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/rails_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/rails_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/rails_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_file/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/rails_minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/rails_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/rails_test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/rr-1.1.2/spec/support/test_helper/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rr-1.1.2.gemspec
